key: 'uiY3WGKVNEaCkntmyikLCALO9O63PBAYcVDwLw0Xu66AgcrEBXab0UANMbWZOsj4'
secret: 'O7zn1HEFTr0e9msT1m52Nu6utZtIkmicRsbUtpSJSdVJrTlLs2NIVLLhiwALXKez'
coin_type: 'BTCUSDT'
aim_time: '2025-01-05  06:30:30'
total_length: 10000
interval: '3m'

