key: 'uiY3WGKVNEaCkntmyikLCALO9O63PBAYcVDwLw0Xu66AgcrEBXab0UANMbWZOsj4'
secret: 'O7zn1HEFTr0e9msT1m52Nu6utZtIkmicRsbUtpSJSdVJrTlLs2NIVLLhiwALXKez'
coin_type: 'ETHUSDT'
aim_time: '2024-10-10  10:00:00'
total_length: 60000
interval: '3m'

total_number: 1000
visual_number: 200
