# # 真实盘
# api_key: 'OqQibH7VeZp0zaWix1Xc4oFKdtpnp9KE8pzHiYIZuQN1za6Ip0VJxKlbwTyfefis'
# api_secret: 'lytyKr5kvRbNepKJOIAONUkC9yJ819HcBIrlhQwiZ07wicz3jqXZfaIvqG5mE3gd'
# 模拟盘
api_key: "2e54bffe0f994be734967a4ea6786b50954bc0229d815d64fb067511b8733be1"
api_secret: "71b59ea564cb76df48ba5d83090e585cdd0b3b02f1923034169f90a48279cd91"
client_testnet: 1 # 0为真实盘，1为模拟盘
coin_type: 'BTCUSDT'
contract_type: 'futures' # 'futures' or 'spot'
# aim_time: '2025-2-10  19:30:00'
# total_length: 10000
# aim_time: '2024-11-1  19:30:00'
# total_length: 60000
# aim_time: '2024-8-1  19:30:00'
# total_length: 100000
interval: '5m'
exhaustive_mode: False # 是否进行穷举,以此优化参数
visualize_mode: True
visual_number: 200



# 设定运行模式:1为实测，0为回测
run_type: 1

backtest_config:
  backtest_start_time: '2025-1-10'
  # backtest_start_time: '2024-11-30'
  backtest_end_time: '2025-02-28'
  backtest_calculate_time: '2025-02-01'

# # 过滤趋势配置参数
# trend_config:
#   interval: '5m'              # 注意此处与顶层 interval 保持一致，可在代码中转换成毫秒
#   enable_filter: 1 # 是否启用过滤
#   delay: 30                    # 生成延迟, 2为无延迟
#   filter_slope: False       # 斜率大小限制: False 表示不过滤
#   slope_threshold: 0.0001      # 最大斜率阈值
#   filter_reverse: True     # 反转限制: False 表示不过滤
#   filter_line_age: True       # 趋势年龄限制
#   min_line_age: 100         # 最小趋势年龄阈值
#   filter_distance: True       # 距离限制，不能太近
#   distance_threshold: 300     # 最小距离阈值
#   filter_trending_line: True  # 处于趋势之中的线不考虑
#   filter_trending_line_number: 5  # 连接当前点趋势的线数量阈值

# 短期测试数据：
# 过滤趋势配置参数
trend_config:
  interval: '5m'              # 注意此处与顶层 interval 保持一致，可在代码中转换成毫秒
  enable_filter: 1 # 是否启用过滤
  delay: 5                   # 生成延迟, 2为无延迟
  filter_slope: False       # 斜率大小限制: False 表示不过滤
  slope_threshold: 0.0001      # 最大斜率阈值
  filter_reverse: True     # 反转限制: False 表示不过滤
  filter_line_age: True       # 趋势年龄限制
  min_line_age: 10        # 最小趋势年龄阈值
  filter_distance: True       # 距离限制，不能太近
  distance_threshold: 15     # 最小距离阈值
  filter_trending_line: True  # 处于趋势之中的线不考虑
  filter_trending_line_number: 2  # 连接当前点趋势的线数量阈值

  

# 交易策略配置参数
trading_config:
  open_times: 2 # 限定单k线开仓次数
  # 0.01就是1%
  fee: 0.001 # 手续费
  stop_loss: 0.002 # 止损
  take_profit: 0.006 # 止盈 # 先做固定止盈

  
  enter_threshold: 0.0003 # 趋势线对应价格与当前价格差距
  leave_threshold: 0.003 # 离开趋势线后，价格与趋势线对应价格差距
  number: 1 # 小于阈值的趋势线数量
  potential_profit: 0.002 # 潜在利润

  trailing_profit_threshold: 0.002 # 移动止损开启利润空间阈值
  trailing_stop_loss: 0.005 # 移动止损可接受的反弹值

  further_sight: 500 # 观察未来50根k线结果出现止损或盈利情况

# 实时交易配置参数
realtime_config:
  total_length: 30000 # 实时交易过去k线长度
