key: 'uiY3WGKVNEaCkntmyikLCALO9O63PBAYcVDwLw0Xu66AgcrEBXab0UANMbWZOsj4'
secret: 'O7zn1HEFTr0e9msT1m52Nu6utZtIkmicRsbUtpSJSdVJrTlLs2NIVLLhiwALXKez'
coin_type: 'BTCUSDT'
# aim_time: '2024-11-1  19:30:00'
# total_length: 60000
aim_time: '2025-2-1  19:30:00'
total_length: 10000
interval: '3m'

visualize_mode: False
visual_number: 200

# 设定运行模式:1为实测，0为回测
run_type: 0

backtest_config:
  backtest_start_time: '2024-11-10  19:30:00'
  backtest_end_time: '2024-12-31  19:30:00'
  backtest_calculate_time: '2024-12-01  19:30:00'

# 趋势配置参数
trend_config:
  delay: 4                    # 生成延迟
  interval: '3m'              # 注意此处与顶层 interval 保持一致，可在代码中转换成毫秒
  filter_slope: True        # 斜率大小限制: False 表示不过滤
  slope_threshold: 0.0001       # 最大斜率阈值
  filter_line_age: true       # 趋势年龄限制
  min_line_age: 40            # 最小趋势年龄阈值
  filter_distance: true       # 距离限制，不能太近
  distance_threshold: 100     # 最小距离阈值
  filter_trending_line: true  # 处于趋势之中的线不考虑
  filter_trending_line_number: 5  # 连接当前点趋势的线数量阈值

# 交易策略配置参数
trading_config:
  fee: 0.002
  stop_loss: 0.0005
  take_profit: 0.001
  high_threshold: 0.0002
  low_threshold: 0.0002
  number: 1
  reverse_percent: 0.02
